CREATE TABLE  "ETUDIANT" (
  "ETUDIANTID" INT NOT NULL,
  "NOM" VARCHAR(45),
  "STATUT" VARCHAR(45),
  PRIMARY KEY ("ETUDIANTID")
  );

CREATE TABLE "TUTEUR" (
  "TUTEURID" INT NOT NULL,
  "NOM" VARCHAR(45),
  "PRENOM" VARCHAR(45),
  "PASSWORD" VARCHAR(45),
  "USERNAME" VARCHAR(45),
  PRIMARY KEY ("TUTEURID"));

CREATE TABLE "STAGE" (
  "STAGEID" INT NOT NULL,
  "GROUPE" VARCHAR(10) NOT NULL,
  "CAHIERDESCHARGES" BOOLEAN NOT NULL,
  "FICHEVISITE" BOOLEAN NOT NULL,
  "FICHEEVALENTR" BOOLEAN NOT NULL,
  "SONDAGEWEB" BOOLEAN NOT NULL,
  "RAPPORTRENDU" BOOLEAN NOT NULL,
  "SOUTENANCE" BOOLEAN NOT NULL,
  "VISITEPLANIF" BOOLEAN NOT NULL,
  "VISITEFAITE" BOOLEAN NOT NULL,
  "DATEDEBUT" VARCHAR(15) NOT NULL,
  "DATEFIN" VARCHAR(15) NOT NULL,
  "NOTETECH" FLOAT NOT NULL,
  "NOTECOM" FLOAT NOT NULL,
  "MAITRESTAGE" VARCHAR(45) NOT NULL,
  "ADRESSE" VARCHAR(45) NOT NULL,
  "DESCRIPTIONMISSION" VARCHAR(200),
  "COMMENTAIRE" VARCHAR(200),
  "ENTREPRISE" VARCHAR(45),
  "TUTEURID" INT NOT NULL,
  "ETUDIANTID" INT NOT NULL,
  PRIMARY KEY ("STAGEID"),
  CONSTRAINT "FK_info_etudiant"
    FOREIGN KEY ("ETUDIANTID")
    REFERENCES "ETUDIANT"("ETUDIANTID"),
  CONSTRAINT "FK_info_prof"
    FOREIGN KEY ("TUTEURID")
    REFERENCES "TUTEUR"("TUTEURID")
);


INSERT INTO TUTEUR (TUTEURID, NOM, PRENOM, PASSWORD, USERNAME)
VALUES (1, 'Augustin', 'Jacques', 'ok', 'ok');

INSERT INTO TUTEUR (TUTEURID, NOM, PRENOM, PASSWORD, USERNAME)
VALUES (2, 'Lahlou', 'Karim', 'ok2', 'ok2');

INSERT INTO TUTEUR (TUTEURID, NOM, PRENOM, PASSWORD, USERNAME)
VALUES (3, 'Khoury', 'Christian', 'ok3', 'ok3');


INSERT INTO ETUDIANT (ETUDIANTID, NOM, STATUT)
VALUES (1, 'Assous Hakim', 'apprenti');

INSERT INTO ETUDIANT (ETUDIANTID, NOM, STATUT)
VALUES (2, 'Poirier Cedric', 'initial');

INSERT INTO ETUDIANT (ETUDIANTID, NOM, STATUT)
VALUES (3, 'Jourdain Hugo', 'initial');

INSERT INTO ETUDIANT (ETUDIANTID, NOM, STATUT)
VALUES (4, 'Vincent Le', 'initial');


INSERT INTO STAGE (STAGEID, GROUPE, CAHIERDESCHARGES, FICHEVISITE, FICHEEVALENTR, SONDAGEWEB, RAPPORTRENDU, SOUTENANCE, VISITEPLANIF, VISITEFAITE, DATEDEBUT, DATEFIN, NOTETECH, NOTECOM, MAITRESTAGE, ADRESSE, TUTEURID, ETUDIANTID, DESCRIPTIONMISSION, COMMENTAIRE, ENTREPRISE)
VALUES (1, 'M2', false, false, true, true, false, false, false, false, '', '', 12.0, 0.0, '', '', 1, 3, 'hugo', 'dddd', NULL);

INSERT INTO STAGE (STAGEID, GROUPE, CAHIERDESCHARGES, FICHEVISITE, FICHEEVALENTR, SONDAGEWEB, RAPPORTRENDU, SOUTENANCE, VISITEPLANIF, VISITEFAITE, DATEDEBUT, DATEFIN, NOTETECH, NOTECOM, MAITRESTAGE, ADRESSE, TUTEURID, ETUDIANTID, DESCRIPTIONMISSION, COMMENTAIRE, ENTREPRISE)
VALUES (2, 'M3', true, true, true, false, false, false, false, false, 'Mars', 'Avril', 0.0, 0.0, '', '', 1, 2, '', '', NULL);
